export PROJECT = ustore-auth
IMPORT_PATH := github.com/wasimkhan042/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/... \
    --link ustore-auth-mysql:ustore-auth-mysql \
    --link ustore-auth-mongo:ustore-auth-mongo \
    ${DEV_IMAGE}
