export PROJECT = ustore-auth
IMPORT_PATH := github.com/wasimkhan042/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link ustore-auth-mongo-db:ustore-auth-mongo-db \
    --link ustore-auth-mysql-db:ustore-auth-mysql-db \
    ${DEV_IMAGE}
